### ISSUE TITLE
not show any option like "Administration" / "Plugins" / "Authentication" / "Odoo login and password integration"

### ISSUE THREAD

**Issue by kartikdanidhariya** [EE/moodle_auth_odoo#1]
hi i am using your module but it not display any option like "Odoo login and password integration" in authantication .
so how can i solve this

**Comment by ludwiktrammer** [comment]
Did Moodle display a screen showing it detected a new plugin?

**Comment by kartikdanidhariya** [comment]
yes it shows 
"Odoo login and password integration"  
status is   "To be installed"

**Comment by ludwiktrammer** [comment]
You need to install it.

**Comment by kartikdanidhariya** [comment]
ok

**Comment by kartikdanidhariya** [comment]
should i click on "upgrade moodle databse now" for install plugin
how can l install plugin in moodle

**Comment by kartikdanidhariya** [comment]
hi i click on "upgrade moodle databse now" than it display "success" mesage
but still in not show any option like "Odoo login and password integration" in authantication .

in plugin overview it show plugin is installed  
i attach image for plugin overview for moodle please check it
![plugin](https://cloud.githubusercontent.com/assets/9051467/8905587/2cb58a0c-3485-11e5-8723-c0cb18d79b88.png)

**Comment by ludwiktrammer** [comment]
Go to Site Administration / Plugins / Authentication / Manage Authentication and click "enable" next to "Odoo login and password integration".

**Comment by kartikdanidhariya** [comment]
hi,
 i click on "enable" so now its enable

after that i provide info like 
database name , URL , amiduser's password
and save after it shows following screens
![after_save](https://cloud.githubusercontent.com/assets/9051467/8930164/2713621c-3549-11e5-9e0f-1a23c38d7662.png)

now from login screen when i enter username and password of odoo user so it shows 
"Invalid login, please try again"

**Comment by kartikdanidhariya** [comment]
ok its my mistake i use https in url replace that from http and it works
thanks for your support
